# .travis.yml
# Copyright (c) 2013-2019 Pablo Acosta-Serafini
# See LICENSE for details
# yamllint disable rule:document-start
# yamllint disable rule:indentation
# yamllint disable rule:line-length

os:
  - linux
  # - osx

sudo: required

dist: trusty

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - git submodule init
  - git submodule update
  - env
  - export PYTHONCMD=python
  - export PYTESTCMD=py.test
  - export PIPCMD=pip
  - export INTERP=py"${TRAVIS_PYTHON_VERSION//./}"
  - export PKG_NAME=$(echo ${TRAVIS_REPO_SLUG} | sed -r "s|.*/(.*)|\1|g")
  - export PYTHON_SITE_PACKAGES=$(${PIPCMD} show pip | grep "Location*" | sed -r "s/^.*Location\W (.*)/\1/g")
  ###
  # Set up environment variables
  ###
  - export REPO_DIR=${TRAVIS_BUILD_DIR}
  - export VIRTUALENV_DIR=$(dirname $(dirname $(dirname ${PYTHON_SITE_PACKAGES})))
  - export BIN_DIR=${VIRTUALENV_DIR}/bin
  - export EXTRA_DIR=$(python -c "from __future__ import print_function; import sys; print(sys.prefix)")/share/${PKG_NAME}
  - export SBIN_DIR=${EXTRA_DIR}/sbin
  - export RESULTS_DIR=${REPO_DIR}/results
  - export SOURCE_DIR=${PYTHON_SITE_PACKAGES}/${PKG_NAME}
  - export TRACER_DIR=${EXTRA_DIR}/docs/support
  - export PYTHONPATH=${PYTHONPATH}:${PYTHON_SITE_PACKAGES}:${EXTRA_DIR}:${EXTRA_DIR}/tests:${EXTRA_DIR}/docs:${EXTRA_DIR}/docs/support
  - export COV_FILE=${SOURCE_DIR}/.coveragerc_ci_${INTERP}
  - export MAIN_REQUIREMENTS_FILE=${REPO_DIR}/requirements/main_${INTERP}.pip
  - export TESTS_REQUIREMENTS_FILE=${REPO_DIR}/requirements/tests_${INTERP}.pip
  - export DOCS_REQUIREMENTS_FILE=${REPO_DIR}/requirements/docs_${INTERP}.pip
  - export AFILE=${EXTRA_DIR}/artifacts_${INTERP}.tar.gz
  - export PYLINT_PLUGINS_DIR=$(if [ -d "${EXTRA_DIR}/pylint_plugins" ]; then echo "${EXTRA_DIR}/pylint_plugins"; fi)
  - export PYLINT_PLUGINS_LIST=$(if [ -d "${EXTRA_DIR}/pylint_plugins" ]; then cd "${EXTRA_DIR}/pylint_plugins" && ls -m *.py | sed 's|.*/||g' | sed 's|, |,|g' | sed 's|\.py||g'; fi)
  - export PYLINT_CLI_APPEND=$(if [ -d "${EXTRA_DIR}/pylint_plugins" ]; then echo "--load-plugins=${PYLINT_PLUGINS_LIST}"; fi)
  - export PYLINT_CMD="pylint --rcfile=$(EXTRA_DIR)/.pylintrc ${PYLINT_CLI_APPEND} --output-format=colorized --reports=no --score=no"
  - echo "PYTHONCMD=${PYTHONCMD}"
  - echo "PIPCMD=${PIPCMD}"
  - echo "PYTESTCMD=${PYTESTCMD}"
  - echo "INTERP=${INTERP}"
  - echo "PKG_NAME=${PKG_NAME}"
  - echo "PYTHON_SITE_PACKAGES=${PYTHON_SITE_PACKAGES}"
  - echo "REPO_DIR=${REPO_DIR}"
  - echo "VIRTUALENV_DIR=${VIRTUALENV_DIR}"
  - echo "BIN_DIR=${BINDIR}"
  - echo "EXTRA_DIR=${EXTRA_DIR}"
  - echo "SBIN_DIR=${SBIN_DIR}"
  - echo "RESULTS_DIR=${RESULTS_DIR}"
  - echo "SOURCE_DIR=${SOURCE_DIR}"
  - echo "TRACER_DIR=${TRACER_DIR}"
  - echo "PYTHONPATH=${PYTHONPATH}"
  - echo "COV_FILE=${COV_FILE}"
  - echo "MAIN_REQUIREMENTS_FILE=${MAIN_REQUIREMENTS_FILE}"
  - echo "TESTS_REQUIREMENTS_FILE=${TESTS_REQUIREMENTS_FILE}"
  - echo "DOCS_REQUIREMENTS_FILE=${DOCS_REQUIREMENTS_FILE}"
  - echo "AFILE=${AFILE}"
  - echo PYLINT_PLUGINS_DIR="${PYLINT_PLUGINS_DIR}"
  - echo PYLINT_PLUGINS_LIST="${PYLINT_PLUGINS_LIST}"
  - echo PYLINT_CLI_APPEND="${PYLINT_CLI_APPEND}"
  - echo PYLINT_CMD="${PYLINT_CMD}"
  ###
  # Install tools and dependencies of package dependencies
  ###
  - sudo apt-get update
  - sudo apt-get install -qq -y hunspell shellcheck

install:
  ###
  # Install package dependencies
  ###
  - ${REPO_DIR}/sbin/gen_req_files.py
  - travis_wait ${PIPCMD} install -r${MAIN_REQUIREMENTS_FILE}
  - travis_wait ${PIPCMD} install -r${TESTS_REQUIREMENTS_FILE}
  - travis_wait ${PIPCMD} install -r${DOCS_REQUIREMENTS_FILE}
  - ${PIPCMD} install codecov
  - ${PIPCMD} freeze

before_script:
  ###
  # Create directories for reports and artifacts
  ###
  - mkdir -p ${RESULTS_DIR}/testresults
  - mkdir -p ${RESULTS_DIR}/codecoverage
  - mkdir -p ${RESULTS_DIR}/artifacts

script:
  ###
  # Install package
  ###
  - cat ${REPO_DIR}/MANIFEST.in
  - ${PYTHONCMD} setup.py sdist
  # Change directory away from repository, otherwise pip does not install package
  - cd ${REPO_DIR}
  - export PKG_VERSION=$(python -c "import os, sys; sys.path.append(os.path.realpath('./'+os.environ['PKG_NAME']));import version; print(version.__version__)")
  - echo "PKG_VERSION=${PKG_VERSION}"
  - cd ${PYTHON_SITE_PACKAGES}
  - ${PIPCMD} install ${REPO_DIR}/dist/${PKG_NAME}-${PKG_VERSION}.tar.gz
  ###
  # Write coverage configuration file
  ###
  - ${PYTHONCMD} ${SBIN_DIR}/coveragerc_manager.py 'ci' 1 ${INTERP} ${PYTHON_SITE_PACKAGES}
  - cat ${COV_FILE}
  - if [ "${INTERP}" == "py26" ]; then
        ${SBIN_DIR}/patch_pylint.py ${PYTHON_SITE_PACKAGES};
    fi
  ###
  # Change to tests sub-directory to mimic Tox conditions
  ###
  - cd ${EXTRA_DIR}/tests
  ###
  # Run tests
  ###
  - ${SBIN_DIR}/cprint.sh line cyan "Testing project code compliance"
  - ${SBIN_DIR}/check_files_compliance.py -tps -d ${SOURCE_DIR} -m ${EXTRA_DIR}
  - ${SBIN_DIR}/cprint.sh line cyan "Testing Pylint compliance";
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} ${SOURCE_DIR}
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} ${SBIN_DIR}
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} ${EXTRA_DIR}/tests
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} ${EXTRA_DIR}/docs/support
  - ${SBIN_DIR}/cprint.sh line cyan "Testing reStructuredText files"
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} --doctest-glob="*.rst" ${EXTRA_DIR}/docs;
  - ${SBIN_DIR}/cprint.sh line cyan "Testing docstrings"
  - PYTHONPATH="$(PYTHONPATH):${PYLINT_PLUGINS_DIR}" ${PYLINT_CMD} --doctest-modules ${SOURCE_DIR}
  # Coverage tests runs all the unit tests, no need to run the non-coverage
  # tests since the report is not being used
  - ${SBIN_DIR}/cprint.sh line cyan "Testing coverage"
  - ${PYTESTCMD} --cov-config ${COV_FILE} --cov ${SOURCE_DIR} --cov-report xml
  - ${SBIN_DIR}/cprint.sh line cyan "Testing documentation"
  - ${SBIN_DIR}/build_docs.py -r -t -d ${SOURCE_DIR}

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - if [ "${CODECOV_TOKEN}" != "" ]; then
        cd ${REPO_DIR};
        cp ${RESULTS_DIR}/codecoverage/coverage.xml ${REPO_DIR}/.;
        export DOT_SOURCE_DIR=${SOURCE_DIR//\//.};
        export DOT_REPO_DIR=${REPO_DIR//\//.};
        sed -r -i -e "s|${SOURCE_DIR}|${REPO_DIR}/${PKG_NAME}|g" coverage.xml;
        sed -r -i -e "s|${DOT_SOURCE_DIR}|${DOT_REPO_DIR}.${PKG_NAME}|g" coverage.xml;
        codecov --token=${CODECOV_TOKEN} --file=${REPO_DIR}/coverage.xml;
    fi

after_failure:
  - ${SBIN_DIR}/zip-artifacts.sh ${INTERP}
  - if [ -f "${AFILE}" ]; then
        ${REPO_DIR}/sbin/dropbox_uploader.sh upload ${AFILE} .;
    else
        echo "Artifacts could not be exported";
    fi
